import {
  Target,
  FileText,
  Search,
  MessageSquare,
  BarChart3,
  Crown,
  Zap,
  Sparkles,
  Lightbulb,
  Award,
  Globe,
  Star,
} from "lucide-react";
import type { PricingConfig, PricingIconMap, PricingAnimationVariants } from "@/types/pricing";

export const PRICING_CONFIG: PricingConfig = {
  title: "Upgrade your plan",
  subtitle: "Need more capabilities for your Freelance business?",
  errorMessages: {
    loadFailed: "Failed to load pricing plans",
    noPlans: "No pricing plans available",
    subscriptionFailed: "An error occurred during subscription. Please try again, if persists, contact support.",
  },
  buttons: {
    tryAgain: "Try Again",
    getStarted: "Get started today",
    currentPlan: "Current plan",
  },
};

export const PRICING_ICON_MAP: PricingIconMap = {
  profile: Target,
  optimization: Target,
  proposal: FileText,
  application: FileText,
  search: Search,
  seo: Search,
  support: MessageSquare,
  help: MessageSquare,
  analytics: BarChart3,
  insight: BarChart3,
  premium: Crown,
  advanced: Crown,
  unlimited: Star,
  infinite: Star,
  priority: Zap,
  fast: Zap,
  ai: Sparkles,
  smart: Sparkles,
  templates: Lightbulb,
  examples: Lightbulb,
  branding: Award,
  custom: Award,
  global: Globe,
  international: Globe,
  default: Star,
};

export const PRICING_ANIMATIONS: PricingAnimationVariants = {
  container: {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        duration: 0.5,
        staggerChildren: 0.1,
      },
    },
  },
  card: {
    hidden: { opacity: 0, y: 20, scale: 0.95 },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: {
        duration: 0.4,
        ease: "easeOut" as const,
      },
    },
  },
  skeleton: {
    hidden: { opacity: 0, scale: 0.95 },
    animate: {
      opacity: 1,
      scale: 1,
      backgroundPosition: ["200% 0", "-200% 0"],
    },
    transition: {
      opacity: { duration: 0.4, delay: 0 },
      scale: { duration: 0.3, delay: 0, ease: "easeOut" as const },
      backgroundPosition: {
        duration: 2,
        repeat: Infinity,
        ease: "linear" as const,
        delay: 0,
      },
    },
  },
  skeletonContainer: {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        duration: 0.5,
        staggerChildren: 0.1,
      },
    },
  },
  skeletonCard: {
    hidden: { opacity: 0, y: 20, scale: 0.95 },
    visible: {
      opacity: 1,
      y: 0,
      scale: 1,
      transition: {
        duration: 0.4,
        ease: "easeOut",
      },
    },
  },
};

export const PRICING_STYLES = {
  container: "flex-1 flex flex-col overflow-y-auto px-6 py-20 lg:px-8 bg-gray-50 w-full",
  header: "mx-auto max-w-4xl text-center",
  title: "text-3xl font-medium mb-3 text-center gap-3",
  subtitle: "text-gray-400",
  errorContainer: "flex-1 overflow-y-auto px-6 py-24 sm:py-32 lg:px-8 bg-gray-50 w-full",
  errorContent: "mx-auto max-w-4xl text-center",
  errorTitle: "text-base text-red-600 font-semibold",
  errorMessage: "mt-2 text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl",
  errorDescription: "mt-6 text-lg leading-8 text-gray-600",
  errorButton: "rounded-full bg-primary px-10 py-3 text-sm text-white shadow-sm hover:bg-primary/80 transition-all duration-300",
  emptyContainer: "px-6 py-24 sm:py-32 lg:px-8 bg-white",
  emptyContent: "mx-auto max-w-4xl text-center",
  emptyTitle: "text-base font-semibold text-primary",
  emptyMessage: "mt-2 text-2xl font-bold tracking-tight text-gray-900 sm:text-3xl",
  emptyDescription: "mt-6 text-lg leading-8 text-gray-600",
  grid: "mx-auto mt-16 grid max-w-lg grid-cols-1 items-center gap-y-6 sm:mt-20 sm:gap-y-0 lg:max-w-4xl lg:grid-cols-2",
  tierCard: "rounded-3xl p-8 ring-1 ring-gray-900/10 sm:p-10",
  tierCardFeatured: "relative bg-gray-900 shadow-2xl",
  tierCardRegular: "bg-white/60 sm:mx-8 lg:mx-0",
  tierCardFirst: "rounded-t-3xl sm:rounded-b-none lg:rounded-tr-none lg:rounded-bl-3xl",
  tierCardLast: "sm:rounded-t-none lg:rounded-tr-3xl lg:rounded-bl-none",
  tierIcon: "p-2 rounded-lg",
  tierIconFeatured: "bg-white/10",
  tierIconRegular: "bg-primary/10",
  tierName: "text-sm",
  tierNameFeatured: "text-white",
  tierNameRegular: "text-black",
  tierPrice: "text-4xl tracking-tight",
  tierPriceFeatured: "text-white",
  tierPriceRegular: "text-gray-900",
  tierPriceUnit: "text-xs leading-none",
  tierPriceUnitFeatured: "text-gray-400",
  tierPriceUnitRegular: "text-gray-500",
  tierDescription: "mt-6 text-sm",
  tierDescriptionFeatured: "text-gray-300",
  tierDescriptionRegular: "text-gray-600",
  featuresList: "mt-8 space-y-3 text-sm sm:mt-10",
  featuresListFeatured: "text-gray-300",
  featuresListRegular: "text-gray-600",
  featureItem: "flex gap-x-5 items-center",
  featureIcon: "p-1 rounded-md",
  featureIconFeatured: "bg-gray-100/20",
  featureIconRegular: "bg-gray-100",
  featureIconColor: "h-3 w-3",
  featureIconColorFeatured: "text-gray-100",
  featureIconColorRegular: "text-primary",
  inheritedFeature: "font-semibold mb-2 flex items-center gap-x-5",
  ctaContainer: "mt-8 sm:mt-10",
  ctaButton: "block rounded-md px-3.5 py-2.5 text-center text-sm focus-visible:outline-2 focus-visible:outline-offset-2 w-full transition-all duration-200",
  ctaButtonFeatured: "bg-indigo-500 text-white shadow-xs hover:bg-indigo-400 focus-visible:outline-indigo-500",
  ctaButtonRegular: "text-indigo-600 ring-1 ring-indigo-200 ring-inset hover:ring-indigo-300 focus-visible:outline-indigo-600",
  ctaCurrent: "block rounded-md px-3.5 py-2.5 text-center text-sm cursor-default",
  ctaCurrentFeatured: "bg-indigo-600/20 text-indigo-200 ring-1 ring-inset ring-indigo-500/30",
  ctaCurrentRegular: "text-indigo-700 ring-1 ring-indigo-200 ring-inset",
  skeletonContainer: "flex-1 overflow-y-auto px-6 py-24 sm:py-32 lg:px-8 bg-gray-50 w-full",
  skeletonContent: "mx-auto max-w-4xl text-center",
  skeletonHeader: "space-y-6 mb-16",
  skeletonTitle: "h-12 w-80 mx-auto",
  skeletonSubtitle: "h-6 w-96 mx-auto",
  skeletonGrid: "grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-4xl mx-auto",
  skeletonCard: "rounded-3xl p-8 sm:p-10",
  skeletonCardFeatured: "bg-slate-900 shadow-2xl ring-1 ring-slate-800",
  skeletonCardRegular: "bg-white/80 shadow-lg ring-1 ring-slate-200",
  skeletonPlanName: "h-7 w-32",
  skeletonPrice: "h-16 w-28",
  skeletonPriceUnit: "h-8 w-16",
  skeletonDescription: "h-5 w-full",
  skeletonFeatures: "space-y-4 pt-4",
  skeletonFeature: "flex items-center gap-3",
  skeletonFeatureIcon: "h-5 w-5 rounded-full",
  skeletonFeatureText: "h-4",
  skeletonCTA: "h-12 w-full mt-8",
} as const;
