/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as SidebarlayoutRouteImport } from './routes/_sidebarlayout'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthProtectRouteImport } from './routes/_auth/_protect'
import { Route as SidebarlayoutProtectedProposalRouteImport } from './routes/_sidebarlayout._protected/proposal'
import { Route as SidebarlayoutProtectedOptimizerRouteImport } from './routes/_sidebarlayout._protected/optimizer'
import { Route as SidebarlayoutProtectedExampleRouteImport } from './routes/_sidebarlayout._protected/example'
import { Route as AuthProtectSignupRouteImport } from './routes/_auth/_protect.signup'
import { Route as AuthProtectLoginRouteImport } from './routes/_auth/_protect.login'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarlayoutRoute = SidebarlayoutRouteImport.update({
  id: '/_sidebarlayout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProtectRoute = AuthProtectRouteImport.update({
  id: '/_auth/_protect',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarlayoutProtectedProposalRoute =
  SidebarlayoutProtectedProposalRouteImport.update({
    id: '/_protected/proposal',
    path: '/proposal',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedOptimizerRoute =
  SidebarlayoutProtectedOptimizerRouteImport.update({
    id: '/_protected/optimizer',
    path: '/optimizer',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedExampleRoute =
  SidebarlayoutProtectedExampleRouteImport.update({
    id: '/_protected/example',
    path: '/example',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const AuthProtectSignupRoute = AuthProtectSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthProtectRoute,
} as any)
const AuthProtectLoginRoute = AuthProtectLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthProtectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/error': typeof ErrorRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof AuthProtectLoginRoute
  '/signup': typeof AuthProtectSignupRoute
  '/example': typeof SidebarlayoutProtectedExampleRoute
  '/optimizer': typeof SidebarlayoutProtectedOptimizerRoute
  '/proposal': typeof SidebarlayoutProtectedProposalRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof AuthProtectLoginRoute
  '/signup': typeof AuthProtectSignupRoute
  '/example': typeof SidebarlayoutProtectedExampleRoute
  '/optimizer': typeof SidebarlayoutProtectedOptimizerRoute
  '/proposal': typeof SidebarlayoutProtectedProposalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_sidebarlayout': typeof SidebarlayoutRouteWithChildren
  '/error': typeof ErrorRoute
  '/_auth/_protect': typeof AuthProtectRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_auth/_protect/login': typeof AuthProtectLoginRoute
  '/_auth/_protect/signup': typeof AuthProtectSignupRoute
  '/_sidebarlayout/_protected/example': typeof SidebarlayoutProtectedExampleRoute
  '/_sidebarlayout/_protected/optimizer': typeof SidebarlayoutProtectedOptimizerRoute
  '/_sidebarlayout/_protected/proposal': typeof SidebarlayoutProtectedProposalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/error'
    | '/forgot-password'
    | '/reset-password'
    | '/'
    | '/login'
    | '/signup'
    | '/example'
    | '/optimizer'
    | '/proposal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/forgot-password'
    | '/reset-password'
    | '/'
    | '/login'
    | '/signup'
    | '/example'
    | '/optimizer'
    | '/proposal'
  id:
    | '__root__'
    | '/_layout'
    | '/_sidebarlayout'
    | '/error'
    | '/_auth/_protect'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_layout/'
    | '/_auth/_protect/login'
    | '/_auth/_protect/signup'
    | '/_sidebarlayout/_protected/example'
    | '/_sidebarlayout/_protected/optimizer'
    | '/_sidebarlayout/_protected/proposal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SidebarlayoutRoute: typeof SidebarlayoutRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  AuthProtectRoute: typeof AuthProtectRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarlayout': {
      id: '/_sidebarlayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_protect': {
      id: '/_auth/_protect'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarlayout/_protected/proposal': {
      id: '/_sidebarlayout/_protected/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof SidebarlayoutProtectedProposalRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/optimizer': {
      id: '/_sidebarlayout/_protected/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof SidebarlayoutProtectedOptimizerRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/example': {
      id: '/_sidebarlayout/_protected/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof SidebarlayoutProtectedExampleRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_auth/_protect/signup': {
      id: '/_auth/_protect/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthProtectSignupRouteImport
      parentRoute: typeof AuthProtectRoute
    }
    '/_auth/_protect/login': {
      id: '/_auth/_protect/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthProtectLoginRouteImport
      parentRoute: typeof AuthProtectRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface SidebarlayoutRouteChildren {
  SidebarlayoutProtectedExampleRoute: typeof SidebarlayoutProtectedExampleRoute
  SidebarlayoutProtectedOptimizerRoute: typeof SidebarlayoutProtectedOptimizerRoute
  SidebarlayoutProtectedProposalRoute: typeof SidebarlayoutProtectedProposalRoute
}

const SidebarlayoutRouteChildren: SidebarlayoutRouteChildren = {
  SidebarlayoutProtectedExampleRoute: SidebarlayoutProtectedExampleRoute,
  SidebarlayoutProtectedOptimizerRoute: SidebarlayoutProtectedOptimizerRoute,
  SidebarlayoutProtectedProposalRoute: SidebarlayoutProtectedProposalRoute,
}

const SidebarlayoutRouteWithChildren = SidebarlayoutRoute._addFileChildren(
  SidebarlayoutRouteChildren,
)

interface AuthProtectRouteChildren {
  AuthProtectLoginRoute: typeof AuthProtectLoginRoute
  AuthProtectSignupRoute: typeof AuthProtectSignupRoute
}

const AuthProtectRouteChildren: AuthProtectRouteChildren = {
  AuthProtectLoginRoute: AuthProtectLoginRoute,
  AuthProtectSignupRoute: AuthProtectSignupRoute,
}

const AuthProtectRouteWithChildren = AuthProtectRoute._addFileChildren(
  AuthProtectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SidebarlayoutRoute: SidebarlayoutRouteWithChildren,
  ErrorRoute: ErrorRoute,
  AuthProtectRoute: AuthProtectRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
