/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as SidebarlayoutRouteImport } from './routes/_sidebarlayout'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as BlogPostBlogpostIdRouteImport } from './routes/blogPost/$blogpostId'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthProtectRouteImport } from './routes/_auth/_protect'
import { Route as SidebarlayoutProtectedUserprofileRouteImport } from './routes/_sidebarlayout._protected/userprofile'
import { Route as SidebarlayoutProtectedResumeRouteImport } from './routes/_sidebarlayout._protected/resume'
import { Route as SidebarlayoutProtectedProposalRouteImport } from './routes/_sidebarlayout._protected/proposal'
import { Route as SidebarlayoutProtectedPricingRouteImport } from './routes/_sidebarlayout._protected/pricing'
import { Route as SidebarlayoutProtectedOptimizerRouteImport } from './routes/_sidebarlayout._protected/optimizer'
import { Route as SidebarlayoutProtectedNotificationsRouteImport } from './routes/_sidebarlayout._protected/notifications'
import { Route as SidebarlayoutProtectedLearnRouteImport } from './routes/_sidebarlayout._protected/learn'
import { Route as SidebarlayoutProtectedExampleRouteImport } from './routes/_sidebarlayout._protected/example'
import { Route as AuthProtectSignupRouteImport } from './routes/_auth/_protect.signup'
import { Route as AuthProtectLoginRouteImport } from './routes/_auth/_protect.login'
import { Route as SidebarlayoutProtectedProposalHistoryProposalIdRouteImport } from './routes/_sidebarlayout._protected/proposalHistory/$proposalId'
import { Route as SidebarlayoutProtectedOptimizerHistoryOptimizerIdRouteImport } from './routes/_sidebarlayout._protected/optimizerHistory/$optimizerId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarlayoutRoute = SidebarlayoutRouteImport.update({
  id: '/_sidebarlayout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const BlogPostBlogpostIdRoute = BlogPostBlogpostIdRouteImport.update({
  id: '/blogPost/$blogpostId',
  path: '/blogPost/$blogpostId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProtectRoute = AuthProtectRouteImport.update({
  id: '/_auth/_protect',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarlayoutProtectedUserprofileRoute =
  SidebarlayoutProtectedUserprofileRouteImport.update({
    id: '/_protected/userprofile',
    path: '/userprofile',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedResumeRoute =
  SidebarlayoutProtectedResumeRouteImport.update({
    id: '/_protected/resume',
    path: '/resume',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedProposalRoute =
  SidebarlayoutProtectedProposalRouteImport.update({
    id: '/_protected/proposal',
    path: '/proposal',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedPricingRoute =
  SidebarlayoutProtectedPricingRouteImport.update({
    id: '/_protected/pricing',
    path: '/pricing',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedOptimizerRoute =
  SidebarlayoutProtectedOptimizerRouteImport.update({
    id: '/_protected/optimizer',
    path: '/optimizer',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedNotificationsRoute =
  SidebarlayoutProtectedNotificationsRouteImport.update({
    id: '/_protected/notifications',
    path: '/notifications',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedLearnRoute =
  SidebarlayoutProtectedLearnRouteImport.update({
    id: '/_protected/learn',
    path: '/learn',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedExampleRoute =
  SidebarlayoutProtectedExampleRouteImport.update({
    id: '/_protected/example',
    path: '/example',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const AuthProtectSignupRoute = AuthProtectSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthProtectRoute,
} as any)
const AuthProtectLoginRoute = AuthProtectLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthProtectRoute,
} as any)
const SidebarlayoutProtectedProposalHistoryProposalIdRoute =
  SidebarlayoutProtectedProposalHistoryProposalIdRouteImport.update({
    id: '/_protected/proposalHistory/$proposalId',
    path: '/proposalHistory/$proposalId',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)
const SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute =
  SidebarlayoutProtectedOptimizerHistoryOptimizerIdRouteImport.update({
    id: '/_protected/optimizerHistory/$optimizerId',
    path: '/optimizerHistory/$optimizerId',
    getParentRoute: () => SidebarlayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/blog': typeof BlogRoute
  '/error': typeof ErrorRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/blogPost/$blogpostId': typeof BlogPostBlogpostIdRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof AuthProtectLoginRoute
  '/signup': typeof AuthProtectSignupRoute
  '/example': typeof SidebarlayoutProtectedExampleRoute
  '/learn': typeof SidebarlayoutProtectedLearnRoute
  '/notifications': typeof SidebarlayoutProtectedNotificationsRoute
  '/optimizer': typeof SidebarlayoutProtectedOptimizerRoute
  '/pricing': typeof SidebarlayoutProtectedPricingRoute
  '/proposal': typeof SidebarlayoutProtectedProposalRoute
  '/resume': typeof SidebarlayoutProtectedResumeRoute
  '/userprofile': typeof SidebarlayoutProtectedUserprofileRoute
  '/optimizerHistory/$optimizerId': typeof SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute
  '/proposalHistory/$proposalId': typeof SidebarlayoutProtectedProposalHistoryProposalIdRoute
}
export interface FileRoutesByTo {
  '/blog': typeof BlogRoute
  '/error': typeof ErrorRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/blogPost/$blogpostId': typeof BlogPostBlogpostIdRoute
  '/': typeof LayoutIndexRoute
  '/login': typeof AuthProtectLoginRoute
  '/signup': typeof AuthProtectSignupRoute
  '/example': typeof SidebarlayoutProtectedExampleRoute
  '/learn': typeof SidebarlayoutProtectedLearnRoute
  '/notifications': typeof SidebarlayoutProtectedNotificationsRoute
  '/optimizer': typeof SidebarlayoutProtectedOptimizerRoute
  '/pricing': typeof SidebarlayoutProtectedPricingRoute
  '/proposal': typeof SidebarlayoutProtectedProposalRoute
  '/resume': typeof SidebarlayoutProtectedResumeRoute
  '/userprofile': typeof SidebarlayoutProtectedUserprofileRoute
  '/optimizerHistory/$optimizerId': typeof SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute
  '/proposalHistory/$proposalId': typeof SidebarlayoutProtectedProposalHistoryProposalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_sidebarlayout': typeof SidebarlayoutRouteWithChildren
  '/blog': typeof BlogRoute
  '/error': typeof ErrorRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/_auth/_protect': typeof AuthProtectRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/blogPost/$blogpostId': typeof BlogPostBlogpostIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_auth/_protect/login': typeof AuthProtectLoginRoute
  '/_auth/_protect/signup': typeof AuthProtectSignupRoute
  '/_sidebarlayout/_protected/example': typeof SidebarlayoutProtectedExampleRoute
  '/_sidebarlayout/_protected/learn': typeof SidebarlayoutProtectedLearnRoute
  '/_sidebarlayout/_protected/notifications': typeof SidebarlayoutProtectedNotificationsRoute
  '/_sidebarlayout/_protected/optimizer': typeof SidebarlayoutProtectedOptimizerRoute
  '/_sidebarlayout/_protected/pricing': typeof SidebarlayoutProtectedPricingRoute
  '/_sidebarlayout/_protected/proposal': typeof SidebarlayoutProtectedProposalRoute
  '/_sidebarlayout/_protected/resume': typeof SidebarlayoutProtectedResumeRoute
  '/_sidebarlayout/_protected/userprofile': typeof SidebarlayoutProtectedUserprofileRoute
  '/_sidebarlayout/_protected/optimizerHistory/$optimizerId': typeof SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute
  '/_sidebarlayout/_protected/proposalHistory/$proposalId': typeof SidebarlayoutProtectedProposalHistoryProposalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/blog'
    | '/error'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/welcome'
    | '/forgot-password'
    | '/reset-password'
    | '/blogPost/$blogpostId'
    | '/'
    | '/login'
    | '/signup'
    | '/example'
    | '/learn'
    | '/notifications'
    | '/optimizer'
    | '/pricing'
    | '/proposal'
    | '/resume'
    | '/userprofile'
    | '/optimizerHistory/$optimizerId'
    | '/proposalHistory/$proposalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blog'
    | '/error'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/welcome'
    | '/forgot-password'
    | '/reset-password'
    | '/blogPost/$blogpostId'
    | '/'
    | '/login'
    | '/signup'
    | '/example'
    | '/learn'
    | '/notifications'
    | '/optimizer'
    | '/pricing'
    | '/proposal'
    | '/resume'
    | '/userprofile'
    | '/optimizerHistory/$optimizerId'
    | '/proposalHistory/$proposalId'
  id:
    | '__root__'
    | '/_layout'
    | '/_sidebarlayout'
    | '/blog'
    | '/error'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/welcome'
    | '/_auth/_protect'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/blogPost/$blogpostId'
    | '/_layout/'
    | '/_auth/_protect/login'
    | '/_auth/_protect/signup'
    | '/_sidebarlayout/_protected/example'
    | '/_sidebarlayout/_protected/learn'
    | '/_sidebarlayout/_protected/notifications'
    | '/_sidebarlayout/_protected/optimizer'
    | '/_sidebarlayout/_protected/pricing'
    | '/_sidebarlayout/_protected/proposal'
    | '/_sidebarlayout/_protected/resume'
    | '/_sidebarlayout/_protected/userprofile'
    | '/_sidebarlayout/_protected/optimizerHistory/$optimizerId'
    | '/_sidebarlayout/_protected/proposalHistory/$proposalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  SidebarlayoutRoute: typeof SidebarlayoutRouteWithChildren
  BlogRoute: typeof BlogRoute
  ErrorRoute: typeof ErrorRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  AuthProtectRoute: typeof AuthProtectRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BlogPostBlogpostIdRoute: typeof BlogPostBlogpostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarlayout': {
      id: '/_sidebarlayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarlayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/blogPost/$blogpostId': {
      id: '/blogPost/$blogpostId'
      path: '/blogPost/$blogpostId'
      fullPath: '/blogPost/$blogpostId'
      preLoaderRoute: typeof BlogPostBlogpostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/_protect': {
      id: '/_auth/_protect'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebarlayout/_protected/userprofile': {
      id: '/_sidebarlayout/_protected/userprofile'
      path: '/userprofile'
      fullPath: '/userprofile'
      preLoaderRoute: typeof SidebarlayoutProtectedUserprofileRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/resume': {
      id: '/_sidebarlayout/_protected/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof SidebarlayoutProtectedResumeRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/proposal': {
      id: '/_sidebarlayout/_protected/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof SidebarlayoutProtectedProposalRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/pricing': {
      id: '/_sidebarlayout/_protected/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SidebarlayoutProtectedPricingRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/optimizer': {
      id: '/_sidebarlayout/_protected/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof SidebarlayoutProtectedOptimizerRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/notifications': {
      id: '/_sidebarlayout/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof SidebarlayoutProtectedNotificationsRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/learn': {
      id: '/_sidebarlayout/_protected/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof SidebarlayoutProtectedLearnRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/example': {
      id: '/_sidebarlayout/_protected/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof SidebarlayoutProtectedExampleRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_auth/_protect/signup': {
      id: '/_auth/_protect/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthProtectSignupRouteImport
      parentRoute: typeof AuthProtectRoute
    }
    '/_auth/_protect/login': {
      id: '/_auth/_protect/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthProtectLoginRouteImport
      parentRoute: typeof AuthProtectRoute
    }
    '/_sidebarlayout/_protected/proposalHistory/$proposalId': {
      id: '/_sidebarlayout/_protected/proposalHistory/$proposalId'
      path: '/proposalHistory/$proposalId'
      fullPath: '/proposalHistory/$proposalId'
      preLoaderRoute: typeof SidebarlayoutProtectedProposalHistoryProposalIdRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
    '/_sidebarlayout/_protected/optimizerHistory/$optimizerId': {
      id: '/_sidebarlayout/_protected/optimizerHistory/$optimizerId'
      path: '/optimizerHistory/$optimizerId'
      fullPath: '/optimizerHistory/$optimizerId'
      preLoaderRoute: typeof SidebarlayoutProtectedOptimizerHistoryOptimizerIdRouteImport
      parentRoute: typeof SidebarlayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface SidebarlayoutRouteChildren {
  SidebarlayoutProtectedExampleRoute: typeof SidebarlayoutProtectedExampleRoute
  SidebarlayoutProtectedLearnRoute: typeof SidebarlayoutProtectedLearnRoute
  SidebarlayoutProtectedNotificationsRoute: typeof SidebarlayoutProtectedNotificationsRoute
  SidebarlayoutProtectedOptimizerRoute: typeof SidebarlayoutProtectedOptimizerRoute
  SidebarlayoutProtectedPricingRoute: typeof SidebarlayoutProtectedPricingRoute
  SidebarlayoutProtectedProposalRoute: typeof SidebarlayoutProtectedProposalRoute
  SidebarlayoutProtectedResumeRoute: typeof SidebarlayoutProtectedResumeRoute
  SidebarlayoutProtectedUserprofileRoute: typeof SidebarlayoutProtectedUserprofileRoute
  SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute: typeof SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute
  SidebarlayoutProtectedProposalHistoryProposalIdRoute: typeof SidebarlayoutProtectedProposalHistoryProposalIdRoute
}

const SidebarlayoutRouteChildren: SidebarlayoutRouteChildren = {
  SidebarlayoutProtectedExampleRoute: SidebarlayoutProtectedExampleRoute,
  SidebarlayoutProtectedLearnRoute: SidebarlayoutProtectedLearnRoute,
  SidebarlayoutProtectedNotificationsRoute:
    SidebarlayoutProtectedNotificationsRoute,
  SidebarlayoutProtectedOptimizerRoute: SidebarlayoutProtectedOptimizerRoute,
  SidebarlayoutProtectedPricingRoute: SidebarlayoutProtectedPricingRoute,
  SidebarlayoutProtectedProposalRoute: SidebarlayoutProtectedProposalRoute,
  SidebarlayoutProtectedResumeRoute: SidebarlayoutProtectedResumeRoute,
  SidebarlayoutProtectedUserprofileRoute:
    SidebarlayoutProtectedUserprofileRoute,
  SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute:
    SidebarlayoutProtectedOptimizerHistoryOptimizerIdRoute,
  SidebarlayoutProtectedProposalHistoryProposalIdRoute:
    SidebarlayoutProtectedProposalHistoryProposalIdRoute,
}

const SidebarlayoutRouteWithChildren = SidebarlayoutRoute._addFileChildren(
  SidebarlayoutRouteChildren,
)

interface AuthProtectRouteChildren {
  AuthProtectLoginRoute: typeof AuthProtectLoginRoute
  AuthProtectSignupRoute: typeof AuthProtectSignupRoute
}

const AuthProtectRouteChildren: AuthProtectRouteChildren = {
  AuthProtectLoginRoute: AuthProtectLoginRoute,
  AuthProtectSignupRoute: AuthProtectSignupRoute,
}

const AuthProtectRouteWithChildren = AuthProtectRoute._addFileChildren(
  AuthProtectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  SidebarlayoutRoute: SidebarlayoutRouteWithChildren,
  BlogRoute: BlogRoute,
  ErrorRoute: ErrorRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  AuthProtectRoute: AuthProtectRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BlogPostBlogpostIdRoute: BlogPostBlogpostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
